version: "3"

services:
  app:
    build: .
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    depends_on:
     - database
    volumes:
      - ./app:/src/app:rw
      - ./pictures:/src/pictures:rw
    ports:
      - 8000:8000
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  database:
    container_name: hotel_db
    image: postgres:14.2
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - 5432:${POSTGRES_PORT}