"""create booking

Revision ID: 07cd1adf5d48
Revises: 12fdc9fda8f0
Create Date: 2022-11-16 13:46:30.528938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cd1adf5d48'
down_revision = '12fdc9fda8f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('arrival_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departure_date', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], ),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('email', 'room_id', name='booking_pk')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###
