"""add room and room characteristics

Revision ID: 07f509e71f3d
Revises: 61cac033b42d
Create Date: 2022-11-12 23:40:37.084771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f509e71f3d'
down_revision = '61cac033b42d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('char_room',
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('number_of_rooms', sa.Integer(), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('square_meters', sa.Integer(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('char_room')
    op.drop_table('room')
    # ### end Alembic commands ###
