"""drop booking

Revision ID: 12fdc9fda8f0
Revises: e563159a055e
Create Date: 2022-11-16 13:39:32.393003

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '12fdc9fda8f0'
down_revision = 'e563159a055e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('booking')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('room_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('arrival_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('departure_date', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email'], ['users.email'], name='booking_email_fkey'),
    sa.ForeignKeyConstraint(['room_id'], ['room.room_id'], name='booking_room_id_fkey'),
    sa.PrimaryKeyConstraint('room_id', name='booking_pkey')
    )
    # ### end Alembic commands ###
