"""remove visitors

Revision ID: 18506e6d38c7
Revises: 7e447668dbd9
Create Date: 2022-11-13 17:13:34.339359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '18506e6d38c7'
down_revision = '7e447668dbd9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('visitors')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitors',
    sa.Column('visitor_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('visitor_id', name='visitors_pkey'),
    sa.UniqueConstraint('email', name='visitors_email_key')
    )
    # ### end Alembic commands ###
