"""add room and room characteristics

Revision ID: 61cac033b42d
Revises: 9f4ef0764c0e
Create Date: 2022-11-12 23:36:43.866295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61cac033b42d'
down_revision = '9f4ef0764c0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
