"""add foreign key for booking

Revision ID: e563159a055e
Revises: 18506e6d38c7
Create Date: 2022-11-13 17:56:35.902361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e563159a055e'
down_revision = '18506e6d38c7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_constraint('booking_email_key', 'booking', type_='unique')
    op.create_foreign_key(None, 'booking', 'users', ['email'], ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.create_unique_constraint('booking_email_key', 'booking', ['email'])
    op.alter_column('booking', 'email',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
